-- Goonhammer Mech Overview ratings seed data
-- Source: https://www.goonhammer.com/battletech-mech-overview-{chassis}/
-- Scraped 2026-02-20

-- Hunchback variants
INSERT INTO external_ratings (variant_id, source, rating, url, notes) VALUES
(102, 'goonhammer', 'D', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-4G: ammo bomb + low speed'),
(103, 'goonhammer', 'B+', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-4H: great value, precision ammo'),
(104, 'goonhammer', 'B+', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-4J: fantastic multi-role LRM mech'),
(105, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-4N: outcompeted by 4H and 4J'),
(106, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-4P: Partyback, 8 MLs but slow'),
(107, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-4SP: decent SRM mech, low mobility'),
(491, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-5H: rocket launchers, funny but limited'),
(492, 'goonhammer', 'F', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-5M: worst upgrade in the game'),
(493, 'goonhammer', 'F', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-5N: bizarre attempt to fix 5M'),
(494, 'goonhammer', 'B+', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-5P: incredible C3+ECM combo'),
(495, 'goonhammer', 'B-', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-5S: LBX-20 with JJs, outcompeted'),
(496, 'goonhammer', 'B+', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-5SG: stealth armor + gauss rifle'),
(497, 'goonhammer', 'A', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-5SS: best MML boat in the game'),
(498, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-6N: ammo bomb in left torso'),
(2505, 'goonhammer', 'C+', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-6P: 6 LPPCs with Radical HSS'),
(499, 'goonhammer', 'A-', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-6S: 6/9/0 with LBX-20, incredible'),
(4065, 'goonhammer', 'B+', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-7X-4: reinforced structure, UAC/10'),
(2918, 'goonhammer', 'B+', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-7R: production 7X-4 with ECM+TAG'),
(4176, 'goonhammer', 'A-', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-7S: 6/9(12)/0 scout/striker'),
(3294, 'goonhammer', 'A+', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-C: one of the best medium mechs'),
(3740, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-4G Shakir: cheapest but empty torso'),
(3747, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-hunchback/', 'HBK-4G Hohiro: decent but outcompeted'),

-- Atlas variants
(8, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-D: overly expensive target'),
(2957, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-A: terrifying SRM but too slow'),
(7, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-D-DC: get a Cyclops instead'),
(1821, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-Dr: merely mediocre'),
(241, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-K: XL engine on assault = bad'),
(1822, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-K2: marginally faster, same problems'),
(1823, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-K3: can jump but overheats more'),
(2426, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-K4: overheats by 10 firing ERPPCs'),
(3363, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-K-DC: command console version'),
(9, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-RS: actual functional Atlas'),
(242, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-S: fixes nothing about the D'),
(243, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-S2: mediocre for the price'),
(3365, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-S3: fine, standard gauss + PPCs'),
(3364, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-S3-DC: best DC Atlas, B- with rules'),
(3366, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-S4: stealth armor, overpriced waste'),
(239, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-C: AS7-K with C3 slave, not better'),
(240, 'goonhammer', 'F', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-CM: funny but terrible'),
(1824, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS8-D: TSM + MMLs, potentially good'),
(3367, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS8-K: ballistic-reinforced armor but XL'),
(3368, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS8-KE: no XL but heat issues'),
(3369, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS8-S: rear firing lasers waste BV'),
(3372, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'Atlas C: not enough ammo or speed'),
(3370, 'goonhammer', 'B', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'Atlas C 2: actually good, functional'),
(3371, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'Atlas C 3: Arrow IV meme, funny C-'),
(3892, 'goonhammer', 'B-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'Samsonov: AC-20 + 2 PPCs, fine'),
(3899, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'Danielle: short ranged, will be kited'),
(4108, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'Jurn: weird weapons, weird role'),
(2663, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'Jedra: light gauss, fine but unmemorable'),
(2705, 'goonhammer', 'A', 'https://www.goonhammer.com/battletech-mech-overview-atlas/', 'AS7-D Ian: double gauss, doesnt suck'),

-- Catapult variants
(35, 'goonhammer', 'B+', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-C1: great intro-tech LRM mech'),
(33, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-A1: no backup weapons'),
(36, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-C1b: disappointing upgrade'),
(290, 'goonhammer', 'B', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-C2: better LRMs but less self-reliant'),
(291, 'goonhammer', 'D', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-C3: Arrow 4 with only 5 shots'),
(37, 'goonhammer', 'F', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-C4: overheats firing LRMs alone'),
(292, 'goonhammer', 'B+', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-C4C: best LRM Catapult'),
(293, 'goonhammer', 'B', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-C5: Arrow 4 with 20 shots, expensive'),
(1973, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-C5A: way too expensive'),
(294, 'goonhammer', 'D', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-C6: plasma rifles, too expensive'),
(38, 'goonhammer', 'B', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-K2: fun PPC cat, no JJs'),
(296, 'goonhammer', 'B', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-K2K: decent ER PPC upgrade'),
(297, 'goonhammer', 'A-', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-K3: oppressively cheap ER PPC sniper'),
(298, 'goonhammer', 'A+', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-K4: C3 heavy PPC headchopper'),
(299, 'goonhammer', 'D', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-K5: MRMs are unreliable'),
(3501, 'goonhammer', 'F', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-K6: ELRMs ruin everything'),
(295, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'CPLT-H2: rocket launchers, could be funny'),
(34, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-catapult/', 'Butterbee: 4 SRM-6s, heat issues'),

-- Shadow Hawk variants
(170, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-2H: underwhelming sampler platter'),
(4124, 'goonhammer', 'F', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-1R: primitive, slow, overpriced'),
(169, 'goonhammer', 'F', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-2D: less armor than most lights'),
(3058, 'goonhammer', 'D', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-2D2: still bad, slightly less so'),
(3059, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-2Hb: perfectly mediocre'),
(3887, 'goonhammer', 'C+', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-2Ht: nimble, hits harder'),
(171, 'goonhammer', 'D', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-2K: worse Griffin, buy a Griffin'),
(3651, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-3H: same damage, slightly less range'),
(3652, 'goonhammer', 'D', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-3H2: slow, too many weapons'),
(2200, 'goonhammer', 'C+', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-3K: heavy PPC headchopper'),
(3060, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-4H: similar to 3K, no C3'),
(2201, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-5D: RAC/5, ok but too expensive'),
(3061, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-5M: LRM-20 fire support'),
(3062, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-5R: Thunderbolts, fun but not good'),
(3063, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-5S: lots of gun, mediocre for price'),
(3064, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-6D: RE lasers, B- vs advanced armor'),
(2202, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-7CS: C3i fire support, too expensive'),
(3065, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-7H: slightly better 2Hb'),
(2203, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-7M: light gauss bad'),
(2204, 'goonhammer', 'C+', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-8L: plasma rifle, 5/8/7, diet Griffin'),
(2205, 'goonhammer', 'B-', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-9D: Tcomp + C3 slave, good in C3'),
(2198, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-11CS: too expensive'),
(2199, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-12C: bizarre but ok'),
(3057, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD C: underwhelming even with Clan tech'),
(2712, 'goonhammer', 'A', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'SHD-2H Berkowitz: best Shadow Hawk'),
(2676, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-shadow-hawk/', 'Sandy: mediocre hero mech'),

-- Wolverine variants
(224, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-6R: inadequate outside 3025'),
(4150, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-1R: primitive, not cool'),
(4151, 'goonhammer', 'F', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-3R: thin armor, slow, short range'),
(2960, 'goonhammer', 'B-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-6D: AC/10 upgrade, decent light hunter'),
(222, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-6K: no JJs hurts'),
(223, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-6M: runs hot, keeps JJs'),
(3214, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-7D: MASC, decent'),
(3216, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-7M: overpriced at 1671 BV'),
(3217, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-7M2: heavy PPC still overpriced'),
(3215, 'goonhammer', 'B+', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-7K: scary knife fighter'),
(2250, 'goonhammer', 'A-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-8C: streak SRMs + C3, excellent'),
(2251, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-8D: RAC/2 with Tcomp, expensive'),
(2252, 'goonhammer', 'C+', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-8K: decent but too expensive'),
(2253, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-9D: no JJs, TAG'),
(2254, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-9K: TSM melee, ok'),
(2255, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-9M: basically the 7M2 again'),
(3218, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-9R: UAC/10, no precision ammo'),
(2256, 'goonhammer', 'B', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-9W: improved JJs, C3i, hard to hit'),
(2257, 'goonhammer', 'B', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-9W2: ECM + C3 slave version'),
(3210, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-10D: RAC/5 but 1935 BV'),
(3211, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-10R: fastest but undergunned'),
(3213, 'goonhammer', 'D', 'https://www.goonhammer.com/battletech-mech-overview-wolverine/', 'WVR-11M: marginal improvement at 1778 BV'),

-- Marauder variants (using Perigrin ratings where both given, since he's the primary reviewer)
(1742, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-1R: overheats, empty side torso'),
(1743, 'goonhammer', 'A-', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-2R: DHS fix everything'),
(3536, 'goonhammer', 'A', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-2T: LB/5 range matches ERPPCs'),
(133, 'goonhammer', 'F', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-3R: worst heavy mech, ammo bomb'),
(130, 'goonhammer', 'C-', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-3D: serviceable, best 3025 Marauder'),
(131, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-3L: halfway house, could be better'),
(132, 'goonhammer', 'C+', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-3M: best 3025 Marauder, cheap brawler'),
(4224, 'goonhammer', 'D-', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-4X: binary laser heat is horrid'),
(3880, 'goonhammer', 'C', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-5CS: ComStar refit, not actively bad'),
(3538, 'goonhammer', 'B', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-5D: good hops, good guns'),
(3537, 'goonhammer', 'A-', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-5D-DC: best with command console'),
(2126, 'goonhammer', 'D+', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-5L: TSM + stealth, too expensive'),
(2127, 'goonhammer', 'B-', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-5M: cheap jumpy pulse mech'),
(2128, 'goonhammer', 'B-', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-5R: RAC + C3, better in C3 lance'),
(3539, 'goonhammer', 'A', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-5S: gauss + ERPPCs, great sniper'),
(2129, 'goonhammer', 'A+', 'https://www.goonhammer.com/battletech-mech-overview-marauder/', 'MAD-5T: RAC/5 + pulse + Tcomp, amazing')
ON CONFLICT DO NOTHING;
